---
title: "Sobre o autor"
description: |
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Olá! Meu nome é **Daniel do Prado Pagotto**! Sou mestre e bacharel em administração e sou encantado pela área de dados e estatística. Há pouco mais de dois anos venho trabalhando quase que diariamente com análise de dados associados a alguns campos de atuação, como **gestão do trabalho em saúde, empreendedorismo e inovação**. Todo meu trabalho tem se baseado primordialmente na linguagem R.    

Apesar do grande interesse, **sempre foi desafiador trabalhar nessa área**, pois os cursos de administração no Brasil ainda não posssuem formações específicas que contribuam para esse campo. Ao longo dos últimos anos, aprendi muita coisa por meio do meu mestrado, livros, tutoriais da internet, cursos da plataforma Datacamp e comunidades de R/estatística. 

Portanto, esse blog nasceu dessa lacuna, ao **democratizar o acesso aos ensinamentos da análise de dados, sobretudo na aplicação da linguagem R às áreas correlatas à minha formação/atuação**. Isso, no entanto, **não exclui a possibilidade de qualquer outra área aprender a partir do ensinamentos aqui passados**. 


Seguem meus contatos